apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200
          image: kibana:7.8.0
          imagePullPolicy: IfNotPresent
          name: kibana
          resources: {}
      dnsPolicy: ClusterFirst
