apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana-service
  name: kibana-service
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30417
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
