apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30290
      port: 5044
      protocol: TCP
      targetPort: 5044
  selector:
    name: logstash
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
