apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:7.8.0
          name: elasticsearch
          resources: {}
          env:
            - name: discovery.type
              value: single-node
      dnsPolicy: ClusterFirst
