apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-service
  name: elasticsearch-service
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30082
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
